---
deployment:
  tasks:
    - export GIT_DIR=/home/aliesmoi/public_html/.git && export GIT_WORK_TREE=/home/aliesmoi/public_html && /usr/bin/git fetch origin && /usr/bin/git clean -fd public/build/ && /usr/bin/git reset --hard origin/main
    - /usr/local/bin/php /home/aliesmoi/public_html/artisan migrate --force
    - /usr/local/bin/php /home/aliesmoi/public_html/artisan optimize:clear
    - /usr/local/bin/php /home/aliesmoi/public_html/artisan view:clear
    - find /home/aliesmoi/public_html/bootstrap/cache -name 'routes*.php' -delete
